---
- name: Load disto specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: [always]

- import_tasks: packages.yml
  tags: [crt]
  
- import_tasks: verify_pair.yml
  tags: [crt,verify]


- import_tasks: materials.yml
  # Only when key matches cert
  when: pubkey_crt.stdout == pubkey_key.stdout
  tags: [crt,ca,chain,key,cert]
