---
- name: Establish public key from certificate
  become: false
  shell: echo "{{ tls_cert_crt }}" | openssl x509 -pubkey -noout
  register: pubkey_crt
  changed_when: false
  check_mode: false

- name: Establish public key from private key
  become: false
  shell: echo "{{ tls_cert_key }}" | openssl pkey -pubout -outform PEM
  register: pubkey_key
  changed_when: false
  check_mode: false
  no_log: true

- debug:
    msg: "Private key and certificate do NOT belong together, there is no use in continuing as it will break your applications"
  failed_when: pubkey_crt.stdout != pubkey_key.stdout
  when: pubkey_crt.stdout != pubkey_key.stdout
